listen_port=9000

health_check_interval=2000
health_check_timeout=500
failure_threshold=3
recovery_threshold=2

algorithm=round_robin

backend=server1,127.0.0.1,8001
backend=server2,127.0.0.1,8002
backend=server3,127.0.0.1,8003
